# Config for test runs
scene: ../scenes/veach-mis/scene.xml

base_render:
  # integrator: RISIntegrator
  integrator: SpatialRISIntegrator
  # size of resampling pool
  pool_size: [ 32, 32, 64, 64 ]
  emitter_only: True
  # number of final shadow rays for each pixel
  shadow_rays: [ 1, 4, 1, 4 ]

#  integrator: SeqRISIntegrator
#  # size of resampling pool
#  pool_size: [ 32, 32, 64, 64 ]
#  sequence_len: [1, 4, 1, 4]
#  emitter_only: True
#  # number of final shadow rays for each pixel
#  shadow_rays: [ 1, 1, 1, 1 ]

ref_render:
  integrator: MyDirectIntegrator
  shading_samples: 50
  shadow_rays: 5

